config/routes.rb
Rails.application.routes.draw do


  resources :character_systems
  resources :worlds
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character_system.rb
class CharacterSystem < ActiveRecord::Base
end

app/models/world.rb
class World < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/character_systems_controller.rb
class CharacterSystemsController < ApplicationController
  before_action :set_character_system, only: [:show, :edit, :update, :destroy]

  # GET /character_systems
  # GET /character_systems.json
  def index
    @character_systems = CharacterSystem.all
  end

  # GET /character_systems/1
  # GET /character_systems/1.json
  def show
  end

  # GET /character_systems/new
  def new
    @character_system = CharacterSystem.new
  end

  # GET /character_systems/1/edit
  def edit
  end

  # POST /character_systems
  # POST /character_systems.json
  def create
    @character_system = CharacterSystem.new(character_system_params)

    respond_to do |format|
      if @character_system.save
        format.html { redirect_to @character_system, notice: 'Character system was successfully created.' }
        format.json { render :show, status: :created, location: @character_system }
      else
        format.html { render :new }
        format.json { render json: @character_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_systems/1
  # PATCH/PUT /character_systems/1.json
  def update
    respond_to do |format|
      if @character_system.update(character_system_params)
        format.html { redirect_to @character_system, notice: 'Character system was successfully updated.' }
        format.json { render :show, status: :ok, location: @character_system }
      else
        format.html { render :edit }
        format.json { render json: @character_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_systems/1
  # DELETE /character_systems/1.json
  def destroy
    @character_system.destroy
    respond_to do |format|
      format.html { redirect_to character_systems_url, notice: 'Character system was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character_system
      @character_system = CharacterSystem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_system_params
      params.require(:character_system).permit(:system, :characters)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @worlds = World.all
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :set_world, only: [:show, :edit, :update, :destroy]

  # GET /worlds
  # GET /worlds.json
  def index
    @worlds = World.all
  end

  # GET /worlds/1
  # GET /worlds/1.json
  def show
  end

  # GET /worlds/new
  def new
    @world = World.new
  end

  # GET /worlds/1/edit
  def edit
  end

  # POST /worlds
  # POST /worlds.json
  def create
    @world = World.new(world_params)

    respond_to do |format|
      if @world.save
        format.html { redirect_to @world, notice: 'World was successfully created.' }
        format.json { render :show, status: :created, location: @world }
      else
        format.html { render :new }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worlds/1
  # PATCH/PUT /worlds/1.json
  def update
    respond_to do |format|
      if @world.update(world_params)
        format.html { redirect_to @world, notice: 'World was successfully updated.' }
        format.json { render :show, status: :ok, location: @world }
      else
        format.html { render :edit }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worlds/1
  # DELETE /worlds/1.json
  def destroy
    @world.destroy
    respond_to do |format|
      format.html { redirect_to worlds_url, notice: 'World was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_world
      @world = World.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def world_params
      params.require(:world).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_systems_helper.rb
module CharacterSystemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/character_systems/_form.html.erb
<%= form_with(model: character_system, local: true) do |form| %>
  <% if character_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character_system.errors.count, "error") %> prohibited this character_system from being saved:</h2>

      <ul>
      <% character_system.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :system %>
    <%= form.text_field :system, id: :character_system_system %>
  </div>

  <div class="field">
    <%= form.label :characters %>
    <%= form.text_area :characters, id: :character_system_characters %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/character_systems/edit.html.erb
<h1>Editing Character System</h1>

<%= render 'form', character_system: @character_system %>

<%= link_to 'Show', @character_system %> |
<%= link_to 'Back', character_systems_path %>

app/views/character_systems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Character Systems</h1>

<table>
  <thead>
    <tr>
      <th>System</th>
      <th>Characters</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_systems.each do |character_system| %>
      <tr>
        <td><%= character_system.system %></td>
        <td><%= character_system.characters %></td>
        <td><%= link_to 'Show', character_system %></td>
        <td><%= link_to 'Edit', edit_character_system_path(character_system) %></td>
        <td><%= link_to 'Destroy', character_system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character System', new_character_system_path %>

app/views/character_systems/new.html.erb
<h1>New Character System</h1>

<%= render 'form', character_system: @character_system %>

<%= link_to 'Back', character_systems_path %>

app/views/character_systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>System:</strong>
  <%= @character_system.system %>
</p>

<p>
  <strong>Characters:</strong>
  <%= @character_system.characters %>
</p>

<%= link_to 'Edit', edit_character_system_path(@character_system) %> |
<%= link_to 'Back', character_systems_path %>

app/views/home/index.html.erb
<!--<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Copper Dragon Inn</title>
        
    </head>-->
    <body>
    	<div class="wrapper">
	    	<div class="main">
		         <header class='header'>
		         	<h1>Welcome to the Copper Dragon Inn!</h1>
		         </header>

		         <div class="article darktext">
		         	<p> Welcome friends! Pull up a chair and settle in for some tales.</p>
		         	<p> There is currently one fantasy setting on this website. Check back for more in the future! 

		         		There are also a large number of characters populating the worlds. You can find them by location, as well as by importance!</p>



		         </div>
	         </div>

	         <div class="sidebar">
	         	<aside>
	         		<h2>What is This?</h2>
	         		<p> The Copper Dragon Inn is a place where you can come to see assorted worlds and fanciful characters, mostly of my own creation! I enjoy worldbuilding, cartography, and character creation. I also love role playing games like D&amp;D, so some characters may have a statblock at the end of their description. If that isn't your cup of tea, no worries, there's plenty here besides that!</p>
	         	</aside>
	         	<nav>

	         		<h2>Links</h2>

	         		<ul>
	         			<li>
	         				<div class="dropWorlds">
	         					<span>
	         						<%= link_to "Worlds", worlds_url%>
	         					</span>
		         				<div class="worlds-content">
				         			<ul>
				         				<% @worlds.each do |world| %>
					         				<li> <%= link_to truncate(world.title, length:10), world%></li>
					         			<%end%>
				         			</ul>
				         		</div>
					        </div>
					    </li>
	         			<li>
	         				<div class="dropChars">
	         					<span>
	         						<%= link_to "Characters", character_systems_url%>
	         					</span>
	         					<div class="characters-content"> 
				         			<ul>
				         				<li> <a href="dnd5char.html" target="_blank" > 5e</a>
				         				</li>
				         				<li> <a href="pathfinderchar.html" target="_blank">Pathfinder</a>
				         				</li>
				         			</ul>
				         		</div>
	         				</div>
	         			</li>
	         		</ul>
	       		 </nav>
	       	</div> 
	       	<footer class="darktext">
	       		 
	       	</footer> 
		</div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inn</title>

	    <%= stylesheet_link_tag 'home.css', media: 'all', 'data-turbolinks-track' => true %>
	    <link href="https://fonts.googleapis.com/css?family=Fondamento|Spectral" rel="stylesheet"> 
	  	
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/worlds/_form.html.erb
<%= form_with(model: world, local: true) do |form| %>
  <% if world.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(world.errors.count, "error") %> prohibited this world from being saved:</h2>

      <ul>
      <% world.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :world_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :world_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worlds/edit.html.erb
<h1>Editing World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Show', @world %> |
<%= link_to 'Back', worlds_path %>

app/views/worlds/index.html.erb
<p id="notice"><%= notice %></p>
<div class="wrapper">
  <div class="main">
    <div class="header">
      <h1>Worlds</h1>
    </div>

      <ul>
        <% @worlds.each do |world| %>
          <li>
            <%= link_to world.title, world %>
          </li>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="sidebar">
    <h2>Expanding Horizons</h2>
    <aside>
      listed here are currently the <%= @worlds.count%> world that I and others have created. 
    </aside>
  </div>
    <br>
  <footer>
    <%= link_to 'New World', new_world_path %>
    <%= link_to "Home", root_url %>
  </footer>
</div>

app/views/worlds/new.html.erb
<h1>New World</h1>

<%= render 'form', world: @world %>

<%= link_to 'Back', worlds_path %>

app/views/worlds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @world.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @world.content %>
</p>

<%= link_to 'Edit', edit_world_path(@world) %> |
<%= link_to 'Back', worlds_path %>